# Generated by Django 3.1.2 on 2020-11-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='NewsletterUser',
        ),
    ]
